import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { ArrowLeft, Calendar, FolderOpen, Plus, Settings, Sparkles } from "lucide-react";
import * as ui from "../../../shared/ui";
import type { DesignProject, DesignProjectInput, DesignProjectSummary } from "../domain/design-project";
import type { ScreenshotProjectSummary } from "../../screenshot-manager/domain/screenshot-project";
import { DesignSimulator } from "../components/DesignSimulator";

const strings={en:{eyebrow:"Kids design studio",title:"Design projects",description:"Generate and inspect implementation-ready GetGo kids interfaces.",new:"New project",projects:"Projects",pages:"Pages",updated:"Last updated",empty:"No design projects yet",name:"Name",desc:"Description",instructions:"Project AI instructions",refs:"Screen capture references",create:"Create project",save:"Save changes",back:"Back to projects",settings:"Project settings",folder:"Open folder",generate:"Generate page with AI",brief:"What should the AI design?",pageName:"Page name",generating:"Generating four designs and assets…",noPages:"No pages yet. Ask AI to create the first page.",delete:"Delete page",preview:"Design preview",portrait:"Portrait",landscape:"Landscape",light:"Light",dark:"Dark",cache:"cached input tokens",tokens:"input tokens"},vi:{eyebrow:"Xưởng thiết kế trẻ em",title:"Dự án thiết kế",description:"Tạo và kiểm tra giao diện GetGo cho trẻ em sẵn sàng triển khai.",new:"Dự án mới",projects:"Dự án",pages:"Trang",updated:"Cập nhật",empty:"Chưa có dự án thiết kế",name:"Tên",desc:"Mô tả",instructions:"Hướng dẫn AI của dự án",refs:"Ảnh chụp tham chiếu",create:"Tạo dự án",save:"Lưu thay đổi",back:"Quay lại dự án",settings:"Cài đặt dự án",folder:"Mở thư mục",generate:"Tạo trang bằng AI",brief:"Bạn muốn AI thiết kế gì?",pageName:"Tên trang",generating:"Đang tạo bốn thiết kế và tài nguyên…",noPages:"Chưa có trang. Hãy yêu cầu AI tạo trang đầu tiên.",delete:"Xóa trang",preview:"Xem thiết kế",portrait:"Dọc",landscape:"Ngang",light:"Sáng",dark:"Tối",cache:"token đầu vào từ bộ nhớ đệm",tokens:"token đầu vào"}} as const;
const parse=(route:string)=>{const m=/^\/designs\/([^/]+)/.exec(route.split("?")[0]);return m?decodeURIComponent(m[1]):null};
const date=(value:string,locale:"en"|"vi")=>new Intl.DateTimeFormat(locale==="vi"?"vi-VN":"en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
export function DesignProjectsPage({locale,initialRoute,onRouteChange}:{locale:"en"|"vi";initialRoute:string;onRouteChange(route:string):void}){
 const copy=strings[locale], projectId=parse(initialRoute), toast=ui.useToast(); const [list,setList]=useState<DesignProjectSummary[]>([]),[project,setProject]=useState<DesignProject|null>(null),[screens,setScreens]=useState<ScreenshotProjectSummary[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[dialog,setDialog]=useState<"project"|"generate"|null>(null); const [values,setValues]=useState<ui.FormValues>({name:"",description:"",instructions:"",references:[],request:""});
 const load=useCallback(async()=>{const [projects,captures]=await Promise.all([window.getgo.listDesignProjects(),window.getgo.listScreenshotProjects()]);setList(projects);setScreens(captures);setProject(projectId?await window.getgo.loadDesignProject(projectId):null)},[projectId]); useEffect(()=>{setLoading(true);void load().catch(e=>setError(String(e))).finally(()=>setLoading(false))},[load]);
 const projectFields=useMemo<ui.FormSchema[]>(()=>[{name:"name",type:"text",label:copy.name,required:true},{name:"description",type:"textarea",label:copy.desc,rows:3},{name:"instructions",type:"textarea",label:copy.instructions,rows:8,helper:locale==="vi"?"Quy định màu sắc, nhân vật, kiểu minh họa, giọng văn và bố cục dùng chung.":"Shared colors, characters, illustration style, voice, and layout rules."},{name:"references",type:"multi-select",label:copy.refs,options:screens.map(x=>({value:x.id,label:`${x.name} · ${x.screenshotCount}`}))}], [copy,locale,screens]); const generationFields=useMemo<ui.FormSchema[]>(()=>[{name:"name",type:"text",label:copy.pageName,required:true},{name:"request",type:"textarea",label:copy.brief,required:true,rows:9}], [copy]);
 const input=():DesignProjectInput=>({name:String(values.name),description:String(values.description||""),instructions:String(values.instructions||""),references:(Array.isArray(values.references)?values.references:[]).map(id=>({screenshotProjectId:String(id),screenshotIds:[]}))});
 async function saveProject(e:FormEvent){e.preventDefault();setBusy(true);setError(null);try{if(project){setProject(await window.getgo.updateDesignProject(project.id,input()));setDialog(null);await load()}else{const made=await window.getgo.createDesignProject(input());setDialog(null);onRouteChange(`/designs/${made.id}`)}}catch(cause){setError(cause instanceof Error?cause.message:String(cause))}finally{setBusy(false)}}
 async function generate(e:FormEvent){e.preventDefault();if(!project)return;setBusy(true);setError(null);try{const result=await window.getgo.generateDesignPage(project.id,{name:String(values.name),request:String(values.request)});setProject(result.project);setDialog(null);setValues({name:"",request:""});await window.getgo.listDesignProjects().then(setList);toast.show({title:copy.generate,description:`${result.usage.cachedInputTokens.toLocaleString()} ${copy.cache} / ${result.usage.inputTokens.toLocaleString()} ${copy.tokens}`})}catch(cause){setError(cause instanceof Error?cause.message:String(cause))}finally{setBusy(false)}}
 const columns=useMemo<ui.DataColumn<DesignProjectSummary>[]>(()=>[{key:"name",title:copy.projects,render:x=><span className="design-project-cell"><strong>{x.name}</strong><small>{x.description}</small></span>},{key:"pages",title:copy.pages,width:100,align:"center",render:x=>x.pageCount},{key:"updated",title:copy.updated,width:220,render:x=><span className="screenshot-date"><Calendar size={15}/>{date(x.updatedAt,locale)}</span>}],[copy,locale]);
 if(loading)return <ui.PageLoading label={copy.title}/>; return <div className="design-projects-page">{!project?<><ui.PageHeader eyebrow={copy.eyebrow} title={copy.title} description={copy.description} actions={<ui.Button variant="primary" icon={<Plus/>} onClick={()=>{setValues({name:"",description:"",instructions:"",references:[]});setDialog("project")}}>{copy.new}</ui.Button>}/>{error&&<ui.ErrorFrame message={error}/>}<ui.Panel><ui.DataTable rows={list} columns={columns} rowKey={x=>x.id} ariaLabel={copy.projects} emptyText={copy.empty} onRowClick={x=>onRouteChange(`/designs/${x.id}`)}/></ui.Panel></>:<><ui.PageHeader eyebrow={copy.eyebrow} title={project.name} description={project.description} leading={<ui.Button variant="icon" icon={<ArrowLeft/>} aria-label={copy.back} onClick={()=>onRouteChange("/designs")}/>} actions={<ui.ControlGroup><ui.Button icon={<Settings/>} onClick={()=>{setValues({name:project.name,description:project.description,instructions:project.instructions,references:project.references.map(x=>x.screenshotProjectId)});setDialog("project")}}>{copy.settings}</ui.Button><ui.Button icon={<FolderOpen/>} onClick={()=>void window.getgo.showDesignProjectFolder(project.id)}>{copy.folder}</ui.Button><ui.Button variant="primary" icon={<Sparkles/>} onClick={()=>{setValues({name:"",request:""});setDialog("generate")}}>{copy.generate}</ui.Button></ui.ControlGroup>}/>{error&&<ui.ErrorFrame message={error}/>}<ui.Panel className="design-simulator-panel"><DesignSimulator locale={locale} project={project}/></ui.Panel></>}{dialog==="project"&&<ui.DialogFrame presentation="modal" title={project?copy.settings:copy.new} busy={busy} error={error} submitLabel={project?copy.save:copy.create} onClose={()=>setDialog(null)} onSubmit={saveProject}><ui.Form fields={projectFields} values={values} onChange={(name,value)=>setValues(x=>({...x,[name]:value}))}/></ui.DialogFrame>}{dialog==="generate"&&<ui.DialogFrame presentation="modal" title={copy.generate} busy={busy} error={error} submitLabel={copy.generate} onClose={()=>!busy&&setDialog(null)} onSubmit={generate}><ui.Form fields={generationFields} values={values} onChange={(name,value)=>setValues(x=>({...x,[name]:value}))}/>{busy&&<p className="design-generating"><Sparkles/>{copy.generating}</p>}</ui.DialogFrame>}</div>
}
