import { useEffect, useLayoutEffect, useRef, useState, type CSSProperties } from "react";
import { ExternalLink, Globe2, RefreshCw } from "lucide-react";
import * as ui from "../../../shared/ui";
import type { DesignProject, DesignTheme, DesignViewport } from "../domain/design-project";

const copy={en:{page:"Demo page",orientation:"Orientation",portrait:"Portrait",landscape:"Landscape",theme:"Theme",light:"Light",dark:"Dark",address:"Preview URL",reload:"Reload preview",open:"Open preview",demo:"Reconstruction",reference:"Design image",empty:"No demo pages yet",emptyDescription:"Generate a page to open it in the simulator."},vi:{page:"Trang demo",orientation:"Hướng",portrait:"Dọc",landscape:"Ngang",theme:"Giao diện",light:"Sáng",dark:"Tối",address:"URL xem trước",reload:"Tải lại bản xem trước",open:"Mở bản xem trước",demo:"Bản dựng",reference:"Ảnh thiết kế",empty:"Chưa có trang demo",emptyDescription:"Tạo một trang để mở trong trình mô phỏng."}} as const;
const sizes={portrait:{width:393,height:852},landscape:{width:1440,height:900}} as const;

export function DesignSimulator({locale,project}:{locale:"en"|"vi";project:DesignProject}){
 const text=copy[locale],[pageId,setPageId]=useState(project.pages[0]?.id??""),[viewport,setViewport]=useState<DesignViewport>("portrait"),[theme,setTheme]=useState<DesignTheme>("light"),[urls,setUrls]=useState({demo:"",reference:""}),[reload,setReload]=useState(0),[scale,setScale]=useState(1);const workspaceRef=useRef<HTMLDivElement>(null),size=sizes[viewport];
 useEffect(()=>{if(!project.pages.some(page=>page.id===pageId))setPageId(project.pages[0]?.id??"")},[pageId,project.pages]);
 useEffect(()=>{if(!pageId){setUrls({demo:"",reference:""});return}void Promise.all([window.getgo.getDesignPreviewUrl(project.id,pageId,viewport,theme),window.getgo.getDesignReferenceUrl(project.id,pageId,viewport,theme)]).then(([demo,reference])=>setUrls({demo,reference}))},[pageId,project.id,theme,viewport,reload]);
 useLayoutEffect(()=>{const workspace=workspaceRef.current;if(!workspace)return;const fit=()=>{const available=Math.max(240,workspace.clientHeight-72);setScale(Math.min(1.25,available/(size.height+32)))};const observer=new ResizeObserver(fit);observer.observe(workspace);fit();return()=>observer.disconnect()},[size.height]);
 if(!project.pages.length)return <div className="design-simulator-empty"><strong>{text.empty}</strong><span>{text.emptyDescription}</span></div>;
 const frameStyle={"--design-width":`${size.width}px`,"--design-height":`${size.height}px`,"--design-scale":scale} as CSSProperties;
 return <div className="design-simulator"><aside className="design-simulator-controls"><label><span>{text.page}</span><ui.Select value={pageId} options={project.pages.map(page=>({value:page.id,label:page.name}))} ariaLabel={text.page} onValueChange={setPageId}/></label><label><span>{text.orientation}</span><ui.SegmentedControl value={viewport} options={[{value:"portrait",label:text.portrait},{value:"landscape",label:text.landscape}]} ariaLabel={text.orientation} onValueChange={value=>setViewport(value as DesignViewport)}/></label><label><span>{text.theme}</span><ui.SegmentedControl value={theme} options={[{value:"light",label:text.light},{value:"dark",label:text.dark}]} ariaLabel={text.theme} onValueChange={value=>setTheme(value as DesignTheme)}/></label></aside><section className="design-simulator-browser"><div className="design-simulator-urlbar"><ui.Button variant="icon" icon={<RefreshCw/>} aria-label={text.reload} title={text.reload} onClick={()=>setReload(value=>value+1)}/><ui.Input leftIcon={<Globe2/>} value={urls.demo} readOnly aria-label={text.address}/><ui.Button variant="icon" icon={<ExternalLink/>} disabled={!urls.demo} aria-label={text.open} title={text.open} onClick={()=>void window.getgo.openExternal(urls.demo)}/></div><div className="design-simulator-workspace" ref={workspaceRef}><div className="design-simulator-track"><PreviewFrame label={text.demo} source={urls.demo} kind="iframe" style={frameStyle} width={size.width} height={size.height} scale={scale}/><PreviewFrame label={text.reference} source={urls.reference} kind="image" style={frameStyle} width={size.width} height={size.height} scale={scale}/></div></div></section></div>;
}

function PreviewFrame({label,source,kind,style,width,height,scale}:{label:string;source:string;kind:"iframe"|"image";style:CSSProperties;width:number;height:number;scale:number}){return <figure className="design-simulator-stage" style={{width:(width+32)*scale,height:(height+32)*scale}}><figcaption>{label}</figcaption><div className="design-simulator-frame" style={style}>{kind==="iframe"?<iframe title={label} src={source}/>:<img alt={label} src={source}/>}</div></figure>}
