import { contextBridge, ipcRenderer } from "electron"
import type { AppSettings, DesktopApi, RepositorySnapshot } from "../core/models.js"

const api: DesktopApi = {
  restartApp: () => ipcRenderer.invoke("app:restart") as Promise<void>,
  getSettings: () => ipcRenderer.invoke("settings:get") as Promise<AppSettings>,
  chooseRepository: () => ipcRenderer.invoke("repository:choose") as Promise<RepositorySnapshot | null>,
  scanRepository: (path?: string) => ipcRenderer.invoke("repository:scan", path) as Promise<RepositorySnapshot>,
  setEnvironment: (environment) => ipcRenderer.invoke("settings:environment", environment) as Promise<AppSettings>,
  setAiProfile: (profile) => ipcRenderer.invoke("settings:ai-profile", profile) as Promise<AppSettings>,
  checkEnvironmentReadiness: () => ipcRenderer.invoke("environment:readiness"),
  getAiUsage: () => ipcRenderer.invoke("ai:usage"),
  showInFolder: (path) => ipcRenderer.invoke("shell:show", path) as Promise<void>,
  showQuizQuestionInFolder: (manifestPath, questionNo) => ipcRenderer.invoke("shell:show-question", manifestPath, questionNo) as Promise<void>,
  readQuizAsset: (manifestPath, assetReference) => ipcRenderer.invoke("quiz-asset:read", manifestPath, assetReference) as Promise<string>,
  readQuizSource: (manifestPath) => ipcRenderer.invoke("quiz-source:read", manifestPath) as Promise<string>,
  saveQuizSource: (manifestPath, source) => ipcRenderer.invoke("quiz-source:save", manifestPath, source) as Promise<void>,
  loadQuizQuestions: (manifestPath) => ipcRenderer.invoke("quiz-questions:load", manifestPath),
  migrateLegacyQuizzes: (contestId) => ipcRenderer.invoke("quiz-questions:migrate-legacy", contestId),
  saveQuizQuestion: (manifestPath, question) => ipcRenderer.invoke("quiz-questions:save", manifestPath, question),
  resetQuizQuestion: (manifestPath, question) => ipcRenderer.invoke("quiz-questions:reset", manifestPath, question),
  openExternal: (url) => ipcRenderer.invoke("shell:open-external", url) as Promise<void>,
  copyText: (text) => ipcRenderer.invoke("clipboard:write", text) as Promise<void>,
  createContest: (settings) => ipcRenderer.invoke("crud:contest:create", settings) as Promise<RepositorySnapshot>,
  updateContest: (id, settings) => ipcRenderer.invoke("crud:contest:update", id, settings) as Promise<RepositorySnapshot>,
  renameContest: (currentId, nextId) => ipcRenderer.invoke("crud:contest:rename", currentId, nextId) as Promise<RepositorySnapshot>,
  deleteContest: (id) => ipcRenderer.invoke("crud:contest:delete", id) as Promise<RepositorySnapshot>,
  createQuiz: (contest, input) => ipcRenderer.invoke("crud:quiz:create", contest, input) as Promise<RepositorySnapshot>,
  updateQuiz: (manifestPath, input) => ipcRenderer.invoke("crud:quiz:update", manifestPath, input) as Promise<RepositorySnapshot>,
  deleteQuiz: (manifestPath) => ipcRenderer.invoke("crud:quiz:delete", manifestPath) as Promise<RepositorySnapshot>,
  getAuthState: () => ipcRenderer.invoke("auth:state"),
  signIn: (email, password) => ipcRenderer.invoke("auth:sign-in", email, password),
  signInWithProvider: (provider) => ipcRenderer.invoke("auth:provider", provider),
  signOut: () => ipcRenderer.invoke("auth:sign-out"),
  changePassword: (password) => ipcRenderer.invoke("auth:change-password", password),
  createDynamicQuestionProposal: (input) => ipcRenderer.invoke("ai:dynamic-question", input),
  fixDynamicQuestion: (input) => ipcRenderer.invoke("ai:fix-dynamic-question", input),
  cancelDynamicQuestionAi: () => ipcRenderer.invoke("ai:cancel-dynamic-question"),
}

contextBridge.exposeInMainWorld("getgo", api)
