import { createServer, type ServerResponse, type Server } from "node:http";
import { promises as fs } from "node:fs";
import path from "node:path";
import { shell, type IpcMain } from "electron";
import type { DesignGenerationInput, DesignProjectInput, DesignTheme, DesignViewport } from "../domain/design-project.js";
import { DesignProjectService } from "./design-project-service.js";
import { DesignAiGenerator } from "./design-ai.js";
import { ScreenshotProjectService } from "../../screenshot-manager/main/screenshot-project-service.js";
import { findRelatedRepository } from "../../../shared/main/repository-locator.js";

const mime=(file:string)=>file.endsWith(".png")?"image/png":/\.jpe?g$/i.test(file)?"image/jpeg":file.endsWith(".css")?"text/css; charset=utf-8":file.endsWith(".js")?"text/javascript; charset=utf-8":file.endsWith(".json")?"application/json":"text/html; charset=utf-8";
const sendFile=async(res:ServerResponse,target:string,allowed:string)=>{const normalized=path.resolve(target);if(!normalized.startsWith(`${path.resolve(allowed)}${path.sep}`))throw new Error("Invalid preview path.");const bytes=await fs.readFile(normalized);res.writeHead(200,{"content-type":mime(normalized),"cache-control":"no-store","access-control-allow-origin":"*"});res.end(bytes);};

export function registerDesignProjectIpc(ipcMain:IpcMain,appPath:string,aiConfig:{apiKey?:string;model?:string;imageModel?:string}){
 let server:Server|undefined,origin="";
 const roots=async()=>{const web=await findRelatedRepository(appPath,{packageName:"tnp-getgo-web",directoryName:"tnp-getgo-web",environmentVariable:"GETGO_WEB_ROOT"});if(!web)throw new Error("GetGo Web repository was not found. Set GETGO_WEB_ROOT.");const legacy=path.join(web,"docs","getgo","kids-friendly-iphone-ui","reconstruction");return{designs:new DesignProjectService(path.join(web,"docs","designs","projects"),legacy),screenshots:new ScreenshotProjectService(path.join(web,"docs","screenshots","projects")),legacy};};
 const ensureServer=async()=>{if(server)return origin;const services=await roots();server=createServer(async(req,res)=>{try{const url=new URL(req.url||"/","http://localhost"),legacy=/^\/legacy\/([a-zA-Z0-9_./-]+)$/.exec(url.pathname),variant=/^\/design\/([a-z0-9-]+)\/([a-z0-9-]+)\/(portrait|landscape)-(light|dark)$/.exec(url.pathname),image=/^\/design-image\/([a-z0-9-]+)\/([a-z0-9-]+)\/(portrait|landscape)-(light|dark)$/.exec(url.pathname),asset=/^\/design\/([a-z0-9-]+)\/([a-z0-9-]+)\/assets\/([a-z0-9-]+\.png)$/.exec(url.pathname);if(legacy){await sendFile(res,path.join(services.legacy,legacy[1]),services.legacy);return;}if(!variant&&!image&&!asset){res.writeHead(404).end("Not found");return;}const match=(variant||image||asset)!,projectId=match[1],pageId=match[2],viewport=(match[3]||"portrait") as DesignViewport,theme=(match[4]||"light") as DesignTheme;if(image){await sendFile(res,await services.designs.resolveImage(projectId,pageId,viewport,theme),services.designs.root);return;}const html=await services.designs.resolveArtifact(projectId,pageId,viewport,theme),target=asset?path.join(path.dirname(html),"assets",asset[3]):html;await sendFile(res,target,services.designs.root);}catch(cause){res.writeHead(500).end(cause instanceof Error?cause.message:String(cause));}});await new Promise<void>((resolve,reject)=>server!.listen(0,"127.0.0.1",resolve).once("error",reject));const address=server.address();if(!address||typeof address==="string")throw new Error("Could not start design preview server.");origin=`http://127.0.0.1:${address.port}`;return origin;};
 ipcMain.handle("designs:projects:list",async()=>(await roots()).designs.list());ipcMain.handle("designs:projects:create",async(_e,input:DesignProjectInput)=>(await roots()).designs.create(input));ipcMain.handle("designs:projects:update",async(_e,id:string,input:DesignProjectInput)=>(await roots()).designs.update(id,input));ipcMain.handle("designs:projects:load",async(_e,id:string)=>(await roots()).designs.load(id));ipcMain.handle("designs:pages:delete",async(_e,id:string,pageId:string)=>(await roots()).designs.removePage(id,pageId));ipcMain.handle("designs:projects:show",async(_e,id:string)=>shell.openPath((await roots()).designs.folder(id)));
 ipcMain.handle("designs:preview:url",async(_e,id:string,pageId:string,viewport:DesignViewport,theme:DesignTheme)=>{const{designs}=await roots(),page=(await designs.load(id)).pages.find(item=>item.id===pageId);return page?.legacyFile?`${await ensureServer()}/legacy/${page.legacyFile}?embed=1&orientation=${viewport}&theme=${theme}`:`${await ensureServer()}/design/${id}/${pageId}/${viewport}-${theme}`;});ipcMain.handle("designs:reference:url",async(_e,id:string,pageId:string,viewport:DesignViewport,theme:DesignTheme)=>{const{designs}=await roots(),page=(await designs.load(id)).pages.find(item=>item.id===pageId);return page?.legacyFile?`${await ensureServer()}/legacy/source/${viewport}/${pageId}.png`:`${await ensureServer()}/design-image/${id}/${pageId}/${viewport}-${theme}`;});
 ipcMain.handle("designs:pages:generate",async(_e,id:string,input:DesignGenerationInput)=>{const{designs,screenshots}=await roots(),project=await designs.load(id);if(!project.references.length)throw new Error("Design generation requires a Screenshot Manager project with completed analysis.");const analyses=await Promise.all(project.references.map(async ref=>{const metadata=await screenshots.loadMetadata(ref.screenshotProjectId),documents=await screenshots.loadAnalysis(ref.screenshotProjectId);if(!documents)throw new Error(`Screenshot project ${ref.screenshotProjectId} has no analysis/pages.json. Generate its analysis before creating a design.`);const selectedRoutes=new Set(ref.screenshotIds.map(screenshotId=>metadata.screenshots.find(item=>item.id===screenshotId)?.route).filter((route):route is string=>Boolean(route)));const pages=selectedRoutes.size?documents.pages.filter(page=>selectedRoutes.has(page.route)):documents.pages;if(!pages.length)throw new Error(`Screenshot project ${ref.screenshotProjectId} has no analyzed pages selected for this design.`);return{projectId:ref.screenshotProjectId,generalRulesMarkdown:documents.generalRulesMarkdown,structureLibrary:documents.structureLibrary as Record<string,unknown>,pages};}));const generated=await new DesignAiGenerator(aiConfig).generate(project,input,analyses),saved=await designs.saveGenerated(id,input,generated);return{...saved,usage:generated.usage};});
}
