import { promises as fs } from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import type { DesignGenerationInput, DesignPage, DesignProject, DesignProjectInput, DesignProjectSummary, DesignTheme, DesignViewport } from "../domain/design-project.js";

const safeId = (value: string) => { if (!/^[a-z0-9-]+$/.test(value)) throw new Error("Invalid design identifier."); return value; };
const text = (value: unknown, label: string, required = false, max = 20_000) => { if (typeof value !== "string") throw new Error(`Invalid ${label}.`); const clean = value.trim(); if (required && !clean) throw new Error(`${label} is required.`); if (clean.length > max) throw new Error(`${label} is too long.`); return clean; };
const slugify = (value: string) => value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "page";

export class DesignProjectService {
  constructor(readonly root: string, readonly legacyRoot?: string) { this.root = path.resolve(root); }
  folder(id: string) { return path.join(this.root, safeId(id)); }
  private manifest(id: string) { return path.join(this.folder(id), "project.json"); }
  private async write(project: DesignProject) { const target = this.manifest(project.id); await fs.mkdir(path.dirname(target), { recursive: true }); await fs.writeFile(`${target}.tmp`, `${JSON.stringify(project, null, 2)}\n`); await fs.rename(`${target}.tmp`, target); }
  async load(id: string): Promise<DesignProject> { const project = JSON.parse(await fs.readFile(this.manifest(safeId(id)), "utf8")) as DesignProject; if (project.schemaVersion !== 1 || project.id !== id || !Array.isArray(project.pages)) throw new Error("The design project is invalid."); return project; }
  private async importLegacy() { if (!this.legacyRoot) return; const marker=path.join(this.root,"kids-ui-reconstruction"); try { await fs.access(path.join(marker,"project.json")); return; } catch {} try { await fs.access(path.join(this.legacyRoot,"index.html")); } catch { return; } const createdAt=new Date().toISOString(); const names=[["login","Login"],["profile","Profile"],["ranking","Ranking"],["student-switch","Student switch"]] as const; const project:DesignProject={schemaVersion:1,id:"kids-ui-reconstruction",name:"GetGo kids UI",description:"Original kid-friendly UI reconstruction, migrated from the standalone design server.",instructions:"Preserve the watercolor storybook illustration style, friendly Vietnamese copy, spacious touch targets, shared navigation, and consistent characters across pages.",references:[],createdAt,updatedAt:createdAt,pages:names.map(([slug,name])=>({id:slug,name,slug,request:"Migrated original design",createdAt,updatedAt:createdAt,artifacts:[],assets:[],specificationFile:"reconstruction.json",legacyFile:`${slug}.html`}))}; await this.write(project); }
  async list(): Promise<DesignProjectSummary[]> { await fs.mkdir(this.root, { recursive: true }); await this.importLegacy(); const entries = await fs.readdir(this.root, { withFileTypes: true }); const values = await Promise.all(entries.filter(x => x.isDirectory()).map(async x => { try { const p = await this.load(x.name); return { id: p.id, name: p.name, description: p.description, pageCount: p.pages.length, updatedAt: p.updatedAt }; } catch { return null; } })); return values.filter((x): x is DesignProjectSummary => Boolean(x)).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); }
  private normalize(input: DesignProjectInput) { return { name: text(input?.name, "project name", true, 120), description: text(input?.description ?? "", "description", false, 500), instructions: text(input?.instructions ?? "", "design instructions"), references: Array.isArray(input?.references) ? input.references.filter(x => x && typeof x.screenshotProjectId === "string").map(x => ({ screenshotProjectId: safeId(x.screenshotProjectId), screenshotIds: Array.isArray(x.screenshotIds) ? x.screenshotIds.filter(id => typeof id === "string") : [] })) : [] }; }
  async create(input: DesignProjectInput) { const now = new Date().toISOString(); const project: DesignProject = { schemaVersion: 1, id: randomUUID(), ...this.normalize(input), createdAt: now, updatedAt: now, pages: [] }; await fs.mkdir(path.join(this.folder(project.id), "pages"), { recursive: true }); await this.write(project); return project; }
  async update(id: string, input: DesignProjectInput) { const project = await this.load(id); Object.assign(project, this.normalize(input), { updatedAt: new Date().toISOString() }); await this.write(project); return project; }
  async saveGenerated(id: string, input: DesignGenerationInput, generated: { specification: unknown; html: Record<string, string>; images: Record<string, string>; assets: Array<{ id: string; name: string; description: string; png: string }> }) { const project = await this.load(id); const pageId = randomUUID(); const slug = `${slugify(text(input.name, "page name", true, 120))}-${pageId.slice(0, 8)}`; const pageFolder = path.join(this.folder(id), "pages", slug); await fs.mkdir(path.join(pageFolder, "assets"), { recursive: true }); const artifacts: DesignPage["artifacts"] = []; for (const viewport of ["portrait", "landscape"] as DesignViewport[]) for (const theme of ["light", "dark"] as DesignTheme[]) { const key = `${viewport}-${theme}`; const htmlFile = `${key}.html`; const imageFile = `${key}.png`; await fs.writeFile(path.join(pageFolder, htmlFile), generated.html[key] ?? ""); await fs.writeFile(path.join(pageFolder, imageFile), Buffer.from(generated.images[key] ?? "", "base64")); artifacts.push({ viewport, theme, htmlFile, imageFile }); }
    const assets = []; for (const asset of generated.assets) { const fileName = `${safeId(asset.id)}.png`; await fs.writeFile(path.join(pageFolder, "assets", fileName), Buffer.from(asset.png, "base64")); assets.push({ id: asset.id, name: asset.name, description: asset.description, fileName: `assets/${fileName}` }); }
    await fs.writeFile(path.join(pageFolder, "design.json"), `${JSON.stringify(generated.specification, null, 2)}\n`); const now = new Date().toISOString(); const page: DesignPage = { id: pageId, name: text(input.name, "page name", true, 120), slug, request: text(input.request, "design request", true), createdAt: now, updatedAt: now, artifacts, assets, specificationFile: "design.json" }; project.pages.push(page); project.updatedAt = now; await this.write(project); return { project, page };
  }
  async removePage(id: string, pageId: string) { const project = await this.load(id); const index = project.pages.findIndex(x => x.id === pageId); if (index < 0) throw new Error("Design page not found."); const [page] = project.pages.splice(index, 1); if(!page.legacyFile){const { shell } = await import("electron"); await shell.trashItem(path.join(this.folder(id), "pages", page.slug));} project.updatedAt = new Date().toISOString(); await this.write(project); return project; }
  async specifications(project:DesignProject) { return Promise.all(project.pages.map(async page=>{try{const file=page.legacyFile&&this.legacyRoot?path.join(this.legacyRoot,page.specificationFile):path.join(this.folder(project.id),"pages",page.slug,page.specificationFile);return {page:page.name,specification:JSON.parse(await fs.readFile(file,"utf8"))};}catch{return {page:page.name,specification:null};}})); }
  resolveArtifact(id: string, pageId: string, viewport: DesignViewport, theme: DesignTheme) { return this.load(id).then(project => { const page = project.pages.find(x => x.id === pageId); if(page?.legacyFile&&this.legacyRoot)return path.join(this.legacyRoot,page.legacyFile); const artifact = page?.artifacts.find(x => x.viewport === viewport && x.theme === theme); if (!page || !artifact) throw new Error("Design preview not found."); return path.join(this.folder(id), "pages", page.slug, artifact.htmlFile); }); }
  resolveImage(id:string,pageId:string,viewport:DesignViewport,theme:DesignTheme){return this.load(id).then(project=>{const page=project.pages.find(x=>x.id===pageId),artifact=page?.artifacts.find(x=>x.viewport===viewport&&x.theme===theme);if(!page||!artifact)throw new Error("Design reference not found.");return path.join(this.folder(id),"pages",page.slug,artifact.imageFile);});}
}
