import { createServer, type ServerResponse, type Server } from "node:http";
import { promises as fs } from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { shell, type IpcMain } from "electron";
import type { DesignGenerationInput, DesignProjectInput, DesignTheme, DesignViewport } from "../domain/design-project.js";
import { DesignProjectService } from "./design-project-service.js";
import { DesignAiGenerator } from "./design-ai.js";
import { ScreenshotProjectService } from "../../screenshot-manager/main/screenshot-project-service.js";
import { findRelatedRepository } from "../../../shared/main/repository-locator.js";

const mime=(file:string)=>file.endsWith(".png")?"image/png":/\.jpe?g$/i.test(file)?"image/jpeg":file.endsWith(".css")?"text/css; charset=utf-8":file.endsWith(".js")?"text/javascript; charset=utf-8":file.endsWith(".json")?"application/json":"text/html; charset=utf-8";
const sendFile=async(res:ServerResponse,target:string,allowed:string)=>{const normalized=path.resolve(target);if(!normalized.startsWith(`${path.resolve(allowed)}${path.sep}`))throw new Error("Invalid preview path.");const bytes=await fs.readFile(normalized);res.writeHead(200,{"content-type":mime(normalized),"cache-control":"no-store","access-control-allow-origin":"*"});res.end(bytes);};

export function registerDesignProjectIpc(ipcMain:IpcMain,appPath:string,aiConfig:{apiKey?:string;model?:string;imageModel?:string}){
 let server:Server|undefined,origin="";
 const roots=async()=>{const web=await findRelatedRepository(appPath,{packageName:"tnp-getgo-web",directoryName:"tnp-getgo-web",environmentVariable:"GETGO_WEB_ROOT"});if(!web)throw new Error("GetGo Web repository was not found. Set GETGO_WEB_ROOT.");const legacy=path.join(web,"docs","getgo","kids-friendly-iphone-ui","reconstruction");return{designs:new DesignProjectService(path.join(web,"docs","designs","projects"),legacy),screenshots:new ScreenshotProjectService(path.join(web,"docs","screenshots","projects")),legacy,styleDemo:path.join(web,"docs","getgo","kids-friendly-iphone-ui","demos","login-light.png")};};
 const ensureServer=async()=>{if(server)return origin;const services=await roots();server=createServer(async(req,res)=>{try{const url=new URL(req.url||"/","http://localhost"),legacy=/^\/legacy\/([a-zA-Z0-9_./-]+)$/.exec(url.pathname),variant=/^\/design\/([a-z0-9-]+)\/([a-z0-9-]+)\/(portrait|landscape)-(light|dark)$/.exec(url.pathname),image=/^\/design-image\/([a-z0-9-]+)\/([a-z0-9-]+)\/(portrait|landscape)-(light|dark)$/.exec(url.pathname),asset=/^\/design\/([a-z0-9-]+)\/([a-z0-9-]+)\/assets\/([a-z0-9-]+\.png)$/.exec(url.pathname);if(legacy){await sendFile(res,path.join(services.legacy,legacy[1]),services.legacy);return;}if(!variant&&!image&&!asset){res.writeHead(404).end("Not found");return;}const match=(variant||image||asset)!,projectId=match[1],pageId=match[2],viewport=(match[3]||"portrait") as DesignViewport,theme=(match[4]||"light") as DesignTheme;if(image){await sendFile(res,await services.designs.resolveImage(projectId,pageId,viewport,theme),services.designs.root);return;}const html=await services.designs.resolveArtifact(projectId,pageId,viewport,theme),target=asset?path.join(path.dirname(html),"assets",asset[3]):html;await sendFile(res,target,services.designs.root);}catch(cause){res.writeHead(500).end(cause instanceof Error?cause.message:String(cause));}});await new Promise<void>((resolve,reject)=>server!.listen(0,"127.0.0.1",resolve).once("error",reject));const address=server.address();if(!address||typeof address==="string")throw new Error("Could not start design preview server.");origin=`http://127.0.0.1:${address.port}`;return origin;};
 ipcMain.handle("designs:projects:list",async()=>(await roots()).designs.list());ipcMain.handle("designs:projects:create",async(_e,input:DesignProjectInput)=>(await roots()).designs.create(input));ipcMain.handle("designs:projects:update",async(_e,id:string,input:DesignProjectInput)=>(await roots()).designs.update(id,input));ipcMain.handle("designs:projects:load",async(_e,id:string)=>(await roots()).designs.load(id));ipcMain.handle("designs:pages:delete",async(_e,id:string,pageId:string)=>(await roots()).designs.removePage(id,pageId));ipcMain.handle("designs:projects:show",async(_e,id:string)=>shell.openPath((await roots()).designs.folder(id)));
 ipcMain.handle("designs:preview:url",async(_e,id:string,pageId:string,viewport:DesignViewport,theme:DesignTheme)=>{const{designs}=await roots(),page=(await designs.load(id)).pages.find(item=>item.id===pageId);return page?.legacyFile?`${await ensureServer()}/legacy/${page.legacyFile}?embed=1&orientation=${viewport}&theme=${theme}`:`${await ensureServer()}/design/${id}/${pageId}/${viewport}-${theme}`;});ipcMain.handle("designs:reference:url",async(_e,id:string,pageId:string,viewport:DesignViewport,theme:DesignTheme)=>{const{designs}=await roots(),page=(await designs.load(id)).pages.find(item=>item.id===pageId);return page?.legacyFile?`${await ensureServer()}/legacy/source/${viewport}/${pageId}.png`:`${await ensureServer()}/design-image/${id}/${pageId}/${viewport}-${theme}`;});
 ipcMain.handle("designs:pages:generate",async(_e,id:string,input:DesignGenerationInput)=>{
  const{designs,screenshots}=await roots(),runId=randomUUID(),startedAt=new Date(),stages:Array<{name:string;status:"passed"|"failed"|"skipped";details:string;elapsedMs:number}>=[];
  const mode=input.mode??"page";const report=(status:"running"|"passed"|"failed",result?:unknown,error?:unknown)=>designs.writeGenerationRun(id,runId,{schemaVersion:1,runId,source:"getgo-tools",mode,status,projectId:id,pageName:input.name,prompt:input.request,startedAt:startedAt.toISOString(),completedAt:status==="running"?null:new Date().toISOString(),elapsedMs:Date.now()-startedAt.getTime(),stages,result:error?undefined:result,error:error?{message:error instanceof Error?error.message:String(error),stack:error instanceof Error?error.stack:undefined}:undefined});
  const stage=async<T>(name:string,action:()=>Promise<T>)=>{const began=Date.now();try{const result=await action();const details=name==="load-art-direction"?"Loaded the complete required art-direction.md contract.":name==="resolve-selected-page-analysis"?(mode==="demo"?"Demo mode confirmed: no Screenshot Manager, pages.json, screenshot, or DOM input was used.":"Resolved only the selected page records from analysis/pages.json."):name==="openai-generate-and-validate"?"OpenAI returned one four-variant page package; schema, semantic actions, theme parity, HTML restrictions, and PNG alpha passed deterministic validation.":name==="persist-and-render-package"?"Saved canonical JSON, assets, four HTML files, and four HTML-rendered demo PNGs.":"Loaded and validated the selected design project.";stages.push({name,status:"passed",details,elapsedMs:Date.now()-began});await report("running");return result;}catch(error){stages.push({name,status:"failed",details:error instanceof Error?error.message:String(error),elapsedMs:Date.now()-began});throw error;}};
  await report("running");
  try{
   const project=await stage("load-design-project",()=>designs.load(id));if(mode==="page"&&!project.references.length)throw new Error("Page mode requires a Screenshot Manager project with completed analysis. Use demo mode for prompt-only generation.");
   const artDirection=await stage("load-art-direction",()=>designs.loadArtDirection(id));
   const analyses=mode==="demo"?await stage("resolve-selected-page-analysis",async()=>[]):await stage("resolve-selected-page-analysis",()=>Promise.all(project.references.map(async ref=>{const metadata=await screenshots.loadMetadata(ref.screenshotProjectId),analyzedPages=await screenshots.loadPagesAnalysis(ref.screenshotProjectId);if(!analyzedPages)throw new Error(`Screenshot project ${ref.screenshotProjectId} has no analysis/pages.json. Generate its analysis before creating a design.`);const selectedRoutes=new Set(ref.screenshotIds.map(screenshotId=>metadata.screenshots.find(item=>item.id===screenshotId)?.route).filter((route):route is string=>Boolean(route)));const pages=selectedRoutes.size?analyzedPages.filter(page=>selectedRoutes.has((page as {route?:unknown}).route as string)):analyzedPages;if(!pages.length)throw new Error(`Screenshot project ${ref.screenshotProjectId} has no analyzed pages selected for this design.`);return{projectId:ref.screenshotProjectId,pages};})));
   const visualReferences=mode!=="reference"?[]:await stage("load-visual-references",async()=>{const selected=project.references.flatMap(ref=>ref.screenshotIds.map(screenshotId=>({ref,screenshotId})));if(selected.length!==1)throw new Error("Reference mode requires exactly one selected current-page screenshot.");const [{ref,screenshotId}]=selected,current=await screenshots.loadScreenshotImage(ref.screenshotProjectId,screenshotId);return[{...current,role:"current-page" as const},{file:(await roots()).styleDemo,mimeType:"image/png",base64:(await fs.readFile((await roots()).styleDemo)).toString("base64"),role:"style-reference" as const}]});
   const generated=await stage("openai-generate-and-validate",()=>new DesignAiGenerator(aiConfig).generate(project,input,analyses,artDirection,visualReferences)),saved=await stage("persist-and-render-package",()=>designs.saveGenerated(id,input,generated)),result={...saved,usage:generated.usage,runId,alphaReport:generated.alphaReport,validationReport:{...generated.validationReport,status:"pass",renderedFromHtml:true},generationManifest:generated.generationManifest};await report("passed",result);return result;
  }catch(error){stages.push(...["load-art-direction","load-visual-references","openai-generate-and-validate","persist-and-render-package"].filter(name=>!stages.some(stage=>stage.name===name)).map(name=>({name,status:"skipped" as const,details:"Skipped because an earlier stage failed or was not required by this mode.",elapsedMs:0})));const runFile=await report("failed",undefined,error);throw new Error(`${error instanceof Error?error.message:String(error)}\nDetailed run report: ${runFile}`,{cause:error});}
 });
}
